export const template = [
  "/Transfer/ABR",
  {
    abn: {
      status: "ABN/@status",
      statusFromDate: "ABN/@ABNStatusFromDate",
      value: "ABN",
    },
    entityType: {
      entityTypeInd: "EntityType/EntityTypeInd",
      entityTypeText: "EntityType/EntityTypeText",
    },
    mainEntity: {
      nonIndividualName: {
        type: "MainEntity/NonIndividualName/@type",
        value: "MainEntity/NonIndividualName/NonIndividualNameText",
      },
      businessAddress: {
        state: "MainEntity/BusinessAddress/AddressDetails/State",
        postcode: "MainEntity/BusinessAddress/AddressDetails/Postcode",
      },
    },
    legalEntity: {
      individualName: {
        type: "LegalEntity/IndividualName/@type",
        givenName: ["LegalEntity/IndividualName/GivenName"],
        familyName: "LegalEntity/IndividualName/FamilyName",
        nameTitle: "LegalEntity/IndividualName/NameTitle",
      },
      businessAddress: {
        state: "LegalEntity/BusinessAddress/AddressDetails/State",
        postcode: "LegalEntity/BusinessAddress/AddressDetails/Postcode",
      },
    },
    asicNumber: {
      type: "ASICNumber/@ASICNumberType",
      value: "ASICNumber",
    },
    gst: {
      status: "GST/@status",
      statusFromDate: "GST/@GSTStatusFromDate",
    },
    dgr: {
      status: "DGR/@status",
      statusFromDate: "DGR/@DGRStatusFromDate",
      nonIndividualName: {
        type: "DGR/NonIndividualName/@type",
        value: "DGR/NonIndividualName/NonIndividualNameText",
      },
    },
    otherEntity: [
      "OtherEntity",
      {
        type: "NonIndividualName/@type",
        value: "NonIndividualName/NonIndividualNameText",
      },
    ],
    recordLastUpdatedDate: "@recordLastUpdatedDate",
  },
];

export enum StatusType {
  cancelled = "CAN",
  active = "ACT",
}

export enum StateEnum {
  AAT = "AAT",
  QLD = "QLD",
  ACT = "ACT",
  NSW = "NSW",
  WA = "WA",
  VIC = "VIC",
  NT = "NT",
  TAS = "TAS",
  SA = "SA",
}

export enum EntityTypeInd {
  ADF = "ADF",
  ARF = "ARF",
  COP = "COP",
  CUT = "CUT",
  DES = "DES",
  DIP = "DIP",
  FGA = "FGA",
  FGD = "FGD",
  FHS = "FHS",
  FPT = "FPT",
  FSA = "FSA",
  GOV = "GOV",
  IND = "IND",
  JVT = "JVT",
  LOC = "LOC",
  LPT = "LPT",
  NRF = "NRF",
  OIE = "OIE",
  PDF = "PDF",
  PRV = "PRV",
  PST = "PST",
  PTR = "PTR",
  PTT = "PTT",
  PUB = "PUB",
  SMF = "SMF",
  SSA = "SSA",
  STA = "STA",
  STR = "STR",
  SUP = "SUP",
  TER = "TER",
  TRT = "TRT",
  UIE = "UIE",
  CGT = "CGT",
  LGA = "LGA",
  LGC = "LGC",
  LGE = "LGE",
  LGP = "LGP",
  LGS = "LGS",
  LGT = "LGT",
  SGA = "SGA",
  SGC = "SGC",
  SGE = "SGE",
  SGP = "SGP",
  SGS = "SGS",
  SGT = "SGT",
  TGA = "TGA",
  TGC = "TGC",
  TGE = "TGE",
  TGP = "TGP",
  TGS = "TGS",
  TGT = "TGT",
  CGA = "CGA",
  CGC = "CGC",
  CGE = "CGE",
  CGP = "CGP",
  CGS = "CGS",
  CCB = "CCB",
  CCC = "CCC",
  CCL = "CCL",
  CCN = "CCN",
  CCO = "CCO",
  CCP = "CCP",
  CCR = "CCR",
  CCS = "CCS",
  CCT = "CCT",
  CCU = "CCU",
  CMT = "CMT",
  CSA = "CSA",
  CSP = "CSP",
  CSS = "CSS",
  CTC = "CTC",
  CTD = "CTD",
  CTF = "CTF",
  CTH = "CTH",
  CTI = "CTI",
  CTL = "CTL",
  CTQ = "CTQ",
  CTT = "CTT",
  CTU = "CTU",
  DIT = "DIT",
  DST = "DST",
  DTT = "DTT",
  FUT = "FUT",
  FXT = "FXT",
  HYT = "HYT",
  LCB = "LCB",
  LCC = "LCC",
  LCL = "LCL",
  LCN = "LCN",
  LCO = "LCO",
  LCP = "LCP",
  LCR = "LCR",
  LCS = "LCS",
  LCT = "LCT",
  LCU = "LCU",
  LSA = "LSA",
  LSP = "LSP",
  LSS = "LSS",
  LTC = "LTC",
  LTD = "LTD",
  LTF = "LTF",
  LTH = "LTH",
  LTI = "LTI",
  LTL = "LTL",
  LTQ = "LTQ",
  LTT = "LTT",
  LTU = "LTU",
  NPF = "NPF",
  POF = "POF",
  PQT = "PQT",
  PUT = "PUT",
  SAF = "SAF",
  SCB = "SCB",
  SCC = "SCC",
  SCL = "SCL",
  SCN = "SCN",
  SCO = "SCO",
  SCP = "SCP",
  SCR = "SCR",
  SCS = "SCS",
  SCT = "SCT",
  SCU = "SCU",
  SSP = "SSP",
  SSS = "SSS",
  STC = "STC",
  STD = "STD",
  STF = "STF",
  STH = "STH",
  STI = "STI",
  STL = "STL",
  STQ = "STQ",
  STT = "STT",
  STU = "STU",
  TCB = "TCB",
  TCC = "TCC",
  TCL = "TCL",
  TCN = "TCN",
  TCO = "TCO",
  TCP = "TCP",
  TCR = "TCR",
  TCS = "TCS",
  TCT = "TCT",
  TCU = "TCU",
  TSA = "TSA",
  TSP = "TSP",
  TSS = "TSS",
  TTC = "TTC",
  TTD = "TTD",
  TTF = "TTF",
  TTH = "TTH",
  TTI = "TTI",
  TTL = "TTL",
  TTQ = "TTQ",
  TTT = "TTT",
  TTU = "TTU",
}

export enum MainOrLegal {
  MAIN = "MAIN",
  LEGAL = "LEGAL",
}

export enum NameType {
  MN = "MN",
  DGR = "DGR",
  LGL = "LGL",
  TRD = "TRD",
  OTN = "OTN",
  BN = "BN",
}
